Task exception was never retrieved
future: <Task finished coro=<get_log() done, defined at C:\Users\aktas\Desktop\restapi\app\app.py:167> exception=NoBrokersAvailable()>
Traceback (most recent call last):
  File "C:\Users\aktas\Desktop\restapi\app\app.py", line 177, in get_log
    bootstrap_servers=['localhost:9092'])
  File "C:\Users\aktas\AppData\Local\Programs\Python\Python37\lib\site-packages\kafka\consumer\group.py", line 356, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "C:\Users\aktas\AppData\Local\Programs\Python\Python37\lib\site-packages\kafka\client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "C:\Users\aktas\AppData\Local\Programs\Python\Python37\lib\site-packages\kafka\client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
Task exception was never retrieved
future: <Task finished coro=<send_log() done, defined at C:\Users\aktas\Desktop\restapi\app\app.py:152> exception=NoBrokersAvailable()>
Traceback (most recent call last):
  File "C:\Users\aktas\Desktop\restapi\app\app.py", line 153, in send_log
    producer = KafkaProducer(bootstrap_servers=['localhost:9092'])
  File "C:\Users\aktas\AppData\Local\Programs\Python\Python37\lib\site-packages\kafka\producer\kafka.py", line 383, in __init__
    **self.config)
  File "C:\Users\aktas\AppData\Local\Programs\Python\Python37\lib\site-packages\kafka\client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "C:\Users\aktas\AppData\Local\Programs\Python\Python37\lib\site-packages\kafka\client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
